version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./model_fr_en:/app/model_fr_en
      - ./model_en_fr:/app/model_en_fr

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
